"""edit table1

Revision ID: 15894e2007e4
Revises: b02690517ee5
Create Date: 2023-08-30 07:42:55.563124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15894e2007e4'
down_revision = 'b02690517ee5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
